name: 'Build LaTeX document'
description: 'Build and publish LaTeX document'
inputs:

  sources:
    description: 'List of tex files to be built'
    required: true

  working_directory:
    description: 'The working directory for building tex files'

  document_filename:
    description: 'The name of the built document file (usually ends with)'

  publish:
    description: 'Publish the release or only draft (false)'
    default: true

runs:

  using: "composite"
  steps:

    - name: Build LaTeX document parts
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ${{ inputs.sources }}
        working_directory: ${{ inputs.working_directory }}

    - name: Upload LaTeX document
      uses: actions/upload-artifact@v4
      id: document-upload-step
      with:
        name: document
        path: ${{ inputs.working_directory }}/${{ inputs.document_filename }}

    - name: Paste document download link into pull request
      uses: actions/github-script@v3
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Document built successfully: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.document-upload-step.outputs.artifact-id }}'
          })

    - name: Gather information for release
      if: github.event_name == 'push'
      id: gather_info
      shell: python
      env:
        GITHUB_REF_NAME: ${{ github.ref-name }}
      run: |
        import os
        branch = os.environ['GITHUB_REF_NAME']
        if branch.startswith('future/')
            print(f'::set-output prerelease=true')
        else:
            print(f'::set-output prerelease=false')

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: ${{ !inputs.publish }}
        prerelease: ${{ steps.gather_info.outputs.prerelease }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ inputs.document_filename }}
        asset_name: ${{ inputs.document_filename }}
        asset_content_type: pdf