name: 'Build LaTeX document'
description: 'Build and publish LaTeX document'
inputs:

  sources:
    description: 'List of tex files to be built (only for the `pull_requrst` and `push` triggers).'
    required: 'true'

  working_directory:
    description: 'The working directory for building tex files (only for the `pull_requrst` and `push` triggers).'
    default: '.'

  latexmk_use_xelatex:
    description: 'Instruct latexmk to use XeLaTeX (only for the `pull_requrst` and `push` triggers).'
    default: 'false'

  document_filename:
    description: 'The name of the built document file (usually ends with ".pdf", only for the `pull_requrst` and `push` triggers)'

  target_branch:
    description: 'The branch where to push the PDF to (only for the `push` trigger).'
    required: 'true'
    default: pdf

  docker_image:
    description: 'The docker image to be used (only for the `pull_requrst` and `push` triggers).'
    required: 'false'

runs:

  using: "composite"
  steps:

    - name: Build LaTeX document parts
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
      uses: xu-cheng/latex-action@v3
      with:
        root_file: ${{ inputs.sources }}
        working_directory: ${{ inputs.working_directory }}
        latexmk_use_xelatex: ${{ inputs.latexmk_use_xelatex }}
        docker_image: ${{ inputs.docker_image }}

    - name: Upload LaTeX document
      if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
      uses: actions/upload-artifact@v4
      id: document-upload-step
      with:
        name: document
        path: ${{ inputs.working_directory }}/${{ inputs.document_filename }}

    - name: Prepare a comment for the pull request
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        echo "{
          \"issue_number\": $ISSUE_NUMBER,
          \"body\": \"Document for $HEAD_SHA built successfully: $URL\"
        }" >> comment.json
      env:
        ISSUE_NUMBER: ${{ github.event.number }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.document-upload-step.outputs.artifact-id }}

    - name: Upload the comment as an artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: comment
        path: comment.json

    - name: Checkout target branch
      if: github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.target_branch }}
        path: target

    - name: Copy PDF
      if: github.event_name == 'push'
      shell: bash
      run: |
        mkdir -p "target/${{ github.ref_name }}"
        cp "${{ inputs.working_directory }}/${{ inputs.document_filename }}" "target/${{ github.ref_name }}/${{ inputs.document_filename }}"

    - name: Build index of the target branch
      if: github.event_name == 'push'
      uses: kostrykin/build-html-index-action@v0.1
      with:
        working-directory: target
        pattern: '**/*.pdf'

    - name: Commit and push the target branch
      if: github.event_name == 'push'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update ${{ github.ref_name }}/${{ inputs.document_filename }}
        repository: target
