name: Build example document

on:

  push:
    paths:
      - 'example/**'
      - '.github/workflows/build.yml'
      - 'action.yml'
      - 'build_index.py'
      
  pull_request:
    branches:
      - 'master'
      - 'future/**'

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref_name == 'master' || contains(github.event.head_commit.message, '[deploy]' )
    permissions:
      contents: write
    
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: ./
        with:
          working_directory: example
          document_filename: example.pdf
          sources: |
            part1.tex
            part2.tex
            example.tex
