name: Build example document

on:
  push:
    paths:
      - 'example/**'
      - '.github/workflows/example.yml'
      - '.github/workflows/action.yml'
  pull_request:
    branches:
      - 'master'
      - 'future-*'

jobs:

  test_example:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref_name == 'master' || startsWith(github.ref_name, 'future-')
    permissions: write-all
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: kostrykin/build-latex-document-action@master
        with:
          working_directory: example
          document_filename: example.pdf
          sources: |
            part1.tex
            part2.tex
            example.tex
          publish: false