name: Post pull request comment

on:

  workflow_run:
    workflows: [Build example document]
    types: [completed]

jobs:

  post_pr_comment:
    runs-on: ubuntu-latest
    permissions: write-all
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:

      - uses: ./
        with:
          github-token: ${{ github.token }}
