name: Post pull request comment

on:

  workflow_run:
    workflows: [Build example document]
    types: [completed]

jobs:

  test_example:
    runs-on: ubuntu-latest
    permissions: write-all
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:

      - name: Download the comment artifact
        uses: actions/download-artifact@v4.1.1
        continue-on-error: true
        with:
          name: comment
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Read comment artifact
        continue-on-error: true
        shell: bash
        run: echo "comment_json=$(jq -c . < comment.json)" >> $GITHUB_ENV

      - name: Create the comment
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: fromJson(env.comment_json).issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fromJson(env.comment_json).body
            })
