name: Post pull request comment

on:

  workflow_run:
    workflows: [Build example document]
    types: [completed]

jobs:

  post_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: ./
